#!/usr/bin/env sh

python querysum.py \
    ../querysum-data/glove/glove.6B.100d.txt \
    ../querysum-data/vocab \
    --mode decode \
    --logdir log \
    --decode_dir ../querysum-data/output/validation \
    --decode_out_dir generated
